# Generated by Django 4.2 on 2025-04-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rewards", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("voucher_type", models.CharField(default="discount", max_length=20)),
                ("tier", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "Percentage"), ("fixed", "Fixed")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "threshold_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("usage_limit_per_user", models.PositiveIntegerField(default=1)),
                ("usage_limit_total", models.PositiveIntegerField(default=1)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True, related_name="vouchers", to="rewards.customer"
                    ),
                ),
                (
                    "shops",
                    models.ManyToManyField(
                        related_name="vouchers", to="authentication.shop"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoucherUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cust_id", models.CharField(max_length=50)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.shop",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="voucher.voucher",
                    ),
                ),
            ],
            options={
                "unique_together": {("voucher", "cust_id", "used_at")},
            },
        ),
    ]
