# Generated by Django 4.2 on 2025-04-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='shop_api_key',
        ),
        migrations.AddField(
            model_name='voucher',
            name='shops',
            field=models.ManyToManyField(related_name='vouchers', to='authentication.shop'),
        ),
    ]
