# Generated by Django 4.2 on 2025-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        ('voucher', '0002_remove_voucher_shop_api_key_voucher_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='voucher',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='rewards.customer'),
        ),
    ]
