# Generated by Django 4.2 on 2025-04-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_remove_voucher_cust_id_voucher_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
