# Generated by Django 4.2 on 2025-04-07 05:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="authentication.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewardCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("max_usage_per_user", models.IntegerField(default=1)),
                ("duration_days", models.IntegerField(blank=True, null=True)),
                (
                    "recurring_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("quarterly", "Quarterly"),
                            ("bi_annual", "Bi-Annual"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="rewards.customer",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="authentication.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("points", models.IntegerField()),
                ("redeemable", models.BooleanField(default=False)),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("is_redeemed", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(
                        default="Purchase processed via API", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "redeemed_at_shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_transactions",
                        to="authentication.shop",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="rewards.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopRewardLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_points", models.PositiveIntegerField(default=0)),
                ("used_points", models.PositiveIntegerField(default=0)),
                ("total_points_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("reward_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_types",
                        to="rewards.rewardcondition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_purchase_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("points", models.IntegerField()),
                ("redeemable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expiration_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Days until points expire, null for no expiration",
                        null=True,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage discount for redeemable codes (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "redeemable_shops",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rules_redeemable_in",
                        to="authentication.shop",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_rules",
                        to="authentication.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards.customer",
                    ),
                ),
                (
                    "reward_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards.rewardtype",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.shop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=10)),
                ("points_per_currency", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_conversions",
                        to="authentication.shop",
                    ),
                ),
            ],
        ),
    ]
