# Generated by Django 4.2 on 2025-04-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shop',
        ),
    ]
