# Generated by Django 4.2 on 2025-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
