# Generated by Django 4.2 on 2025-04-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_remove_customer_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
