# Generated by Django 4.2 on 2025-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="description",
            field=models.CharField(
                default="Purchase processed via API", max_length=255
            ),
        ),
    ]
