# Generated by Django 4.2 on 2025-04-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_wallettransaction_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallettransaction",
            name="expires_at",
        ),
    ]
