# Generated by Django 4.2 on 2025-04-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_wallet_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='points',
        ),
    ]
