# Generated by Django 4.2 on 2025-04-07 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_remove_wallet_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='purchase_points',
            new_name='points',
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='rewards.customer'),
        ),
    ]
