# Generated by Django 4.2 on 2025-04-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0005_wallettransaction_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserule",
            name="expiration_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days until points expire, null for no expiration",
                null=True,
            ),
        ),
    ]
