# Generated by Django 4.2 on 2025-04-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('rewards', '0005_rename_purchase_points_wallet_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='authentication.shop'),
            preserve_default=False,
        ),
    ]
