# Generated by Django 4.2 on 2025-04-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('rewards', '0006_customer_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='rewards.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('customer', 'shop')},
        ),
    ]
