# Generated by Django 4.2 on 2025-04-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0006_purchaserule_expiration_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserule",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage discount for redeemable codes (0-100)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
